// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var TNF$Game = require("./TNF.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function AIPlayer(MyGame) {
  var maxDepth = 2;
  var alphaBetaMinimax = function (s, depth, alpha, beta) {
    var possibleLegalMoves = Curry._1(MyGame.legalMoves, s);
    var match = Curry._1(MyGame.gameStatus, s);
    if (match.TAG === /* Win */0) {
      return Curry._1(MyGame.estimateValue, s);
    }
    if (depth === 0) {
      return Curry._1(MyGame.estimateValue, s);
    }
    if (!possibleLegalMoves) {
      return Curry._1(MyGame.estimateValue, s);
    }
    if (match._0 === /* P1 */0) {
      var _alom = possibleLegalMoves;
      var _alphaVal = alpha;
      var _bestVal = -Pervasives.infinity;
      while(true) {
        var bestVal = _bestVal;
        var alphaVal = _alphaVal;
        var alom = _alom;
        if (!alom) {
          return bestVal;
        }
        var currVal = alphaBetaMinimax(Curry._2(MyGame.nextState, s, alom.hd), depth - 1 | 0, alphaVal, beta);
        var bestOverall = currVal > bestVal ? currVal : bestVal;
        var bestAlpha = currVal > alphaVal ? currVal : alphaVal;
        if (bestAlpha >= beta) {
          return bestOverall;
        }
        _bestVal = bestOverall;
        _alphaVal = bestAlpha;
        _alom = alom.tl;
        continue ;
      };
    }
    var _alom$1 = possibleLegalMoves;
    var _betaVal = beta;
    var _bestVal$1 = Pervasives.infinity;
    while(true) {
      var bestVal$1 = _bestVal$1;
      var betaVal = _betaVal;
      var alom$1 = _alom$1;
      if (!alom$1) {
        return bestVal$1;
      }
      var currVal$1 = alphaBetaMinimax(Curry._2(MyGame.nextState, s, alom$1.hd), depth - 1 | 0, alpha, betaVal);
      var bestOverall$1 = currVal$1 < bestVal$1 ? currVal$1 : bestVal$1;
      var bestBeta = currVal$1 < betaVal ? currVal$1 : betaVal;
      if (bestBeta <= alpha) {
        return bestOverall$1;
      }
      _bestVal$1 = bestOverall$1;
      _betaVal = bestBeta;
      _alom$1 = alom$1.tl;
      continue ;
    };
  };
  var nextMove = function (s) {
    var possibleLegalMoves = Curry._1(MyGame.legalMoves, s);
    if (!possibleLegalMoves) {
      return Pervasives.failwith("THERE ARE NO LEGAL MOVES!");
    }
    if (!possibleLegalMoves.tl) {
      return possibleLegalMoves.hd;
    }
    var scoresOfPossibleLegalMoves = List.map((function (m) {
            return [
                    m,
                    alphaBetaMinimax(Curry._2(MyGame.nextState, s, m), maxDepth - 1 | 0, -Pervasives.infinity, Pervasives.infinity)
                  ];
          }), possibleLegalMoves);
    var chooseBestMove = function (valueComparison, movesAndScores) {
      return List.fold_left((function (currBest, nextPossible) {
                    if (Curry._2(valueComparison, nextPossible[1], currBest[1])) {
                      return nextPossible;
                    } else {
                      return currBest;
                    }
                  }), List.hd(movesAndScores), List.tl(movesAndScores));
    };
    var match = Curry._1(MyGame.gameStatus, s);
    if (match.TAG === /* Win */0) {
      return Pervasives.failwith("GAME IS OVER!");
    } else if (match._0) {
      return chooseBestMove((function (a, b) {
                      return a < b;
                    }), scoresOfPossibleLegalMoves)[0];
    } else {
      return chooseBestMove((function (a, b) {
                      return a > b;
                    }), scoresOfPossibleLegalMoves)[0];
    }
  };
  return {
          PlayerGame: MyGame,
          speedOfControl: 0,
          maxDepth: maxDepth,
          alphaBetaMinimax: alphaBetaMinimax,
          nextMove: nextMove,
          playerName: "SpikeTyson"
        };
}

var maxDepth = 2;

function alphaBetaMinimax(s, depth, alpha, beta) {
  var possibleLegalMoves = Curry._1(TNF$Game.TNF.legalMoves, s);
  var match = Curry._1(TNF$Game.TNF.gameStatus, s);
  if (match.TAG === /* Win */0) {
    return Curry._1(TNF$Game.TNF.estimateValue, s);
  }
  if (depth === 0) {
    return Curry._1(TNF$Game.TNF.estimateValue, s);
  }
  if (!possibleLegalMoves) {
    return Curry._1(TNF$Game.TNF.estimateValue, s);
  }
  if (match._0 === /* P1 */0) {
    var _alom = possibleLegalMoves;
    var _alphaVal = alpha;
    var _bestVal = -Pervasives.infinity;
    while(true) {
      var bestVal = _bestVal;
      var alphaVal = _alphaVal;
      var alom = _alom;
      if (!alom) {
        return bestVal;
      }
      var currVal = alphaBetaMinimax(Curry._2(TNF$Game.TNF.nextState, s, alom.hd), depth - 1 | 0, alphaVal, beta);
      var bestOverall = currVal > bestVal ? currVal : bestVal;
      var bestAlpha = currVal > alphaVal ? currVal : alphaVal;
      if (bestAlpha >= beta) {
        return bestOverall;
      }
      _bestVal = bestOverall;
      _alphaVal = bestAlpha;
      _alom = alom.tl;
      continue ;
    };
  }
  var _alom$1 = possibleLegalMoves;
  var _betaVal = beta;
  var _bestVal$1 = Pervasives.infinity;
  while(true) {
    var bestVal$1 = _bestVal$1;
    var betaVal = _betaVal;
    var alom$1 = _alom$1;
    if (!alom$1) {
      return bestVal$1;
    }
    var currVal$1 = alphaBetaMinimax(Curry._2(TNF$Game.TNF.nextState, s, alom$1.hd), depth - 1 | 0, alpha, betaVal);
    var bestOverall$1 = currVal$1 < bestVal$1 ? currVal$1 : bestVal$1;
    var bestBeta = currVal$1 < betaVal ? currVal$1 : betaVal;
    if (bestBeta <= alpha) {
      return bestOverall$1;
    }
    _bestVal$1 = bestOverall$1;
    _betaVal = bestBeta;
    _alom$1 = alom$1.tl;
    continue ;
  };
}

function nextMove(s) {
  var possibleLegalMoves = Curry._1(TNF$Game.TNF.legalMoves, s);
  if (!possibleLegalMoves) {
    return Pervasives.failwith("THERE ARE NO LEGAL MOVES!");
  }
  if (!possibleLegalMoves.tl) {
    return possibleLegalMoves.hd;
  }
  var scoresOfPossibleLegalMoves = List.map((function (m) {
          return [
                  m,
                  alphaBetaMinimax(Curry._2(TNF$Game.TNF.nextState, s, m), maxDepth - 1 | 0, -Pervasives.infinity, Pervasives.infinity)
                ];
        }), possibleLegalMoves);
  var chooseBestMove = function (valueComparison, movesAndScores) {
    return List.fold_left((function (currBest, nextPossible) {
                  if (Curry._2(valueComparison, nextPossible[1], currBest[1])) {
                    return nextPossible;
                  } else {
                    return currBest;
                  }
                }), List.hd(movesAndScores), List.tl(movesAndScores));
  };
  var match = Curry._1(TNF$Game.TNF.gameStatus, s);
  if (match.TAG === /* Win */0) {
    return Pervasives.failwith("GAME IS OVER!");
  } else if (match._0) {
    return chooseBestMove((function (a, b) {
                    return a < b;
                  }), scoresOfPossibleLegalMoves)[0];
  } else {
    return chooseBestMove((function (a, b) {
                    return a > b;
                  }), scoresOfPossibleLegalMoves)[0];
  }
}

var playerName = "SpikeTyson";

var TestAIPlayer = {
  PlayerGame: TNF$Game.TNF,
  speedOfControl: 0,
  maxDepth: maxDepth,
  alphaBetaMinimax: alphaBetaMinimax,
  nextMove: nextMove,
  playerName: playerName
};

var TestGame;

var MyAIPlayer = {
  PlayerGame: TNF$Game.TNF,
  nextMove: nextMove,
  playerName: playerName
};

exports.AIPlayer = AIPlayer;
exports.TestGame = TestGame;
exports.TestAIPlayer = TestAIPlayer;
exports.MyAIPlayer = MyAIPlayer;
/* TNF-Game Not a pure module */
