// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");

function printGreen(s) {
  return Pervasives.print_string("\x1b[32m" + (s + "\x1b[0m\n"));
}

function printRed(s) {
  return Pervasives.print_string("\x1b[31m" + (s + "\x1b[0m\n"));
}

function checkExpect(actual, expected, message) {
  if (Caml_obj.caml_equal(actual, expected)) {
    return printGreen("checkExpectSuccess: " + message);
  } else {
    printRed("checkExpectFail: " + message);
    printRed("expected output: ");
    console.log(expected);
    printRed("actual output: ");
    console.log(actual);
    return ;
  }
}

function checkError(input, expect) {
  try {
    Curry._1(input, undefined);
    return Pervasives.failwith("Error did not occur");
  }
  catch (raw_err){
    var err = Caml_js_exceptions.internalToOCamlException(raw_err);
    if (err.RE_EXN_ID === "Failure") {
      var err$1 = err._1;
      if (err$1 === expect) {
        return printGreen("checkErrorSuccess");
      } else if (err$1 === "Error did not occur") {
        return printRed("Error did not occur");
      } else {
        return printRed("checkErrorFail. Expected error: " + (expect + ("; Actual error: " + err$1)));
      }
    }
    throw err;
  }
}

function parseInput(s) {
  var indices = function (n) {
    var indicesHelper = function (n) {
      if (n <= 0) {
        return /* [] */0;
      } else {
        return {
                hd: n - 1 | 0,
                tl: indicesHelper(n - 1 | 0)
              };
      }
    };
    return List.rev(indicesHelper(n));
  };
  return List.map((function (i) {
                var param = Caml_string.get(s, i);
                if (param !== 46) {
                  if (param !== 70) {
                    if (param !== 84) {
                      return Pervasives.failwith("invalid character in initialization string");
                    } else {
                      return 1;
                    }
                  } else {
                    return 2;
                  }
                } else {
                  return 0;
                }
              }), indices(s.length));
}

exports.printGreen = printGreen;
exports.printRed = printRed;
exports.checkExpect = checkExpect;
exports.checkError = checkError;
exports.parseInput = parseInput;
/* No side effect */
