// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");

function HumanPlayer(MyGame) {
  var getInputJSLine = (function() {
        const readlineSync = require('readline-sync');
        const rl = readlineSync;
        var ans = rl.question('What move do you want to make? ');
        return ans;
    });
  var nextMove = function (s) {
    while(true) {
      var input = Curry._1(getInputJSLine, undefined);
      if (input === "exit") {
        return Pervasives.failwith("Exiting Game REPL");
      }
      try {
        return Curry._2(MyGame.moveOfString, input, s);
      }
      catch (raw_msg){
        var msg = Caml_js_exceptions.internalToOCamlException(raw_msg);
        if (msg.RE_EXN_ID !== "Failure") {
          return Pervasives.failwith("Unexpected Error, Closing Game REPL");
        }
        console.log(msg._1);
        continue ;
      }
    };
  };
  return {
          PlayerGame: MyGame,
          getInputJSLine: getInputJSLine,
          nextMove: nextMove,
          playerName: "Alex"
        };
}

exports.HumanPlayer = HumanPlayer;
/* No side effect */
