// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$String = require("bs-platform/lib/js/string.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var CS17SetupGame$Game = require("./CS17SetupGame.bs.js");

function initialState(s) {
  var convertIntToGameSpace = function (param) {
    switch (param) {
      case 0 :
          return /* Empty */2;
      case 1 :
          return /* Toad */0;
      case 2 :
          return /* Frog */1;
      default:
        return Pervasives.failwith("INVALID FORMAT");
    }
  };
  var parsed = CS17SetupGame$Game.parseInput(s);
  var initialBoard = List.map(convertIntToGameSpace, parsed);
  return {
          board: initialBoard,
          who: /* P1 */0,
          usedNothingP1: false,
          usedNothingP2: false
        };
}

CS17SetupGame$Game.checkExpect(initialState("TT..FF"), {
      board: {
        hd: /* Toad */0,
        tl: {
          hd: /* Toad */0,
          tl: {
            hd: /* Empty */2,
            tl: {
              hd: /* Empty */2,
              tl: {
                hd: /* Frog */1,
                tl: {
                  hd: /* Frog */1,
                  tl: /* [] */0
                }
              }
            }
          }
        }
      },
      who: /* P1 */0,
      usedNothingP1: false,
      usedNothingP2: false
    }, "Success!");

CS17SetupGame$Game.checkExpect(initialState("TTT....FFF"), {
      board: {
        hd: /* Toad */0,
        tl: {
          hd: /* Toad */0,
          tl: {
            hd: /* Toad */0,
            tl: {
              hd: /* Empty */2,
              tl: {
                hd: /* Empty */2,
                tl: {
                  hd: /* Empty */2,
                  tl: {
                    hd: /* Empty */2,
                    tl: {
                      hd: /* Frog */1,
                      tl: {
                        hd: /* Frog */1,
                        tl: {
                          hd: /* Frog */1,
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      who: /* P1 */0,
      usedNothingP1: false,
      usedNothingP2: false
    }, "Success!");

function stringOfPlayer(param) {
  if (param) {
    return "P2";
  } else {
    return "P1";
  }
}

CS17SetupGame$Game.checkExpect("P1", "P1", "Success!");

CS17SetupGame$Game.checkExpect("P2", "P2", "Success!");

function stringOfState(st) {
  var cells = List.map((function (i) {
          switch (i) {
            case /* Toad */0 :
                return "T";
            case /* Frog */1 :
                return "F";
            case /* Empty */2 :
                return ".";
            
          }
        }), st.board);
  return $$String.concat(" ", cells) + ("\nturn: " + (
            st.who ? "P2" : "P1"
          ));
}

CS17SetupGame$Game.checkExpect(stringOfState({
          board: {
            hd: /* Toad */0,
            tl: {
              hd: /* Toad */0,
              tl: {
                hd: /* Empty */2,
                tl: {
                  hd: /* Empty */2,
                  tl: {
                    hd: /* Frog */1,
                    tl: {
                      hd: /* Frog */1,
                      tl: /* [] */0
                    }
                  }
                }
              }
            }
          },
          who: /* P1 */0,
          usedNothingP1: false,
          usedNothingP2: false
        }), "T T . . F F\nturn: P1", "Success!");

CS17SetupGame$Game.checkExpect(stringOfState({
          board: {
            hd: /* Toad */0,
            tl: {
              hd: /* Toad */0,
              tl: {
                hd: /* Toad */0,
                tl: {
                  hd: /* Toad */0,
                  tl: {
                    hd: /* Empty */2,
                    tl: {
                      hd: /* Empty */2,
                      tl: {
                        hd: /* Empty */2,
                        tl: {
                          hd: /* Empty */2,
                          tl: {
                            hd: /* Empty */2,
                            tl: {
                              hd: /* Frog */1,
                              tl: {
                                hd: /* Frog */1,
                                tl: {
                                  hd: /* Frog */1,
                                  tl: {
                                    hd: /* Frog */1,
                                    tl: /* [] */0
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          who: /* P1 */0,
          usedNothingP1: false,
          usedNothingP2: false
        }), "T T T T . . . . . F F F F\nturn: P1", "Success!");

function stringOfMove(m) {
  return String(m);
}

CS17SetupGame$Game.checkExpect(String(6), "6", "Success!");

CS17SetupGame$Game.checkExpect(String(8), "8", "Success!");

CS17SetupGame$Game.checkExpect(String(2), "2", "Success!");

function legalMoves(s) {
  var accessGameSpace = function (bd, n, len) {
    if (n < 1 || n > len) {
      return Pervasives.failwith("ILLEGAL MOVE: INDEX IS OUT OF BOUNDS!");
    } else {
      return List.nth(bd, n - 1 | 0);
    }
  };
  var canToadMove = function (bd, i, len) {
    if (i < len && accessGameSpace(bd, i + 1 | 0, len) === /* Empty */2) {
      return true;
    } else if ((i + 1 | 0) < len && accessGameSpace(bd, i + 1 | 0, len) === /* Frog */1) {
      return accessGameSpace(bd, i + 2 | 0, len) === /* Empty */2;
    } else {
      return false;
    }
  };
  var canFrogMove = function (bd, i, len) {
    if (i > 1 && accessGameSpace(bd, i - 1 | 0, len) === /* Empty */2) {
      return true;
    } else if (i > 2 && accessGameSpace(bd, i - 1 | 0, len) === /* Toad */0) {
      return accessGameSpace(bd, i - 2 | 0, len) === /* Empty */2;
    } else {
      return false;
    }
  };
  var bd = s.board;
  var n = List.length(bd);
  var match = s.who;
  var moves = match ? (
      !s.usedNothingP2 ? ({
            hd: 0,
            tl: /* [] */0
          }) : /* [] */0
    ) : (
      !s.usedNothingP1 ? ({
            hd: 0,
            tl: /* [] */0
          }) : /* [] */0
    );
  var _index = 1;
  var _currentMoves = moves;
  while(true) {
    var currentMoves = _currentMoves;
    var index = _index;
    if (index > n) {
      return currentMoves;
    }
    var piece = accessGameSpace(bd, index, n);
    var match$1 = s.who;
    var canPieceMove = match$1 ? piece === /* Frog */1 && canFrogMove(bd, index, n) : piece === /* Toad */0 && canToadMove(bd, index, n);
    var moves$1 = canPieceMove ? Pervasives.$at(currentMoves, {
            hd: index,
            tl: /* [] */0
          }) : currentMoves;
    _currentMoves = moves$1;
    _index = index + 1 | 0;
    continue ;
  };
}

CS17SetupGame$Game.checkExpect(legalMoves({
          board: {
            hd: /* Toad */0,
            tl: {
              hd: /* Toad */0,
              tl: {
                hd: /* Empty */2,
                tl: {
                  hd: /* Empty */2,
                  tl: {
                    hd: /* Frog */1,
                    tl: {
                      hd: /* Frog */1,
                      tl: /* [] */0
                    }
                  }
                }
              }
            }
          },
          who: /* P1 */0,
          usedNothingP1: false,
          usedNothingP2: false
        }), {
      hd: 0,
      tl: {
        hd: 2,
        tl: /* [] */0
      }
    }, "Success!");

CS17SetupGame$Game.checkExpect(legalMoves({
          board: {
            hd: /* Toad */0,
            tl: {
              hd: /* Toad */0,
              tl: {
                hd: /* Toad */0,
                tl: {
                  hd: /* Empty */2,
                  tl: {
                    hd: /* Empty */2,
                    tl: {
                      hd: /* Toad */0,
                      tl: {
                        hd: /* Empty */2,
                        tl: {
                          hd: /* Empty */2,
                          tl: {
                            hd: /* Frog */1,
                            tl: {
                              hd: /* Empty */2,
                              tl: {
                                hd: /* Frog */1,
                                tl: {
                                  hd: /* Frog */1,
                                  tl: {
                                    hd: /* Frog */1,
                                    tl: /* [] */0
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          who: /* P2 */1,
          usedNothingP1: true,
          usedNothingP2: true
        }), {
      hd: 9,
      tl: {
        hd: 11,
        tl: /* [] */0
      }
    }, "Success!");

function moveOfString(str, st) {
  var currMove;
  try {
    currMove = Caml_format.caml_int_of_string(str);
  }
  catch (exn){
    currMove = Pervasives.failwith("NEED TO INPUT AN INTEGER!");
  }
  var _param = legalMoves(st);
  while(true) {
    var param = _param;
    if (!param) {
      return Pervasives.failwith("ILLEGAL MOVE!");
    }
    if (param.hd === currMove) {
      return currMove;
    }
    _param = param.tl;
    continue ;
  };
}

CS17SetupGame$Game.checkExpect(moveOfString("2", {
          board: {
            hd: /* Toad */0,
            tl: {
              hd: /* Toad */0,
              tl: {
                hd: /* Empty */2,
                tl: {
                  hd: /* Empty */2,
                  tl: {
                    hd: /* Frog */1,
                    tl: {
                      hd: /* Frog */1,
                      tl: /* [] */0
                    }
                  }
                }
              }
            }
          },
          who: /* P1 */0,
          usedNothingP1: false,
          usedNothingP2: false
        }), 2, "Success!");

CS17SetupGame$Game.checkExpect(moveOfString("5", {
          board: {
            hd: /* Toad */0,
            tl: {
              hd: /* Toad */0,
              tl: {
                hd: /* Empty */2,
                tl: {
                  hd: /* Empty */2,
                  tl: {
                    hd: /* Frog */1,
                    tl: {
                      hd: /* Frog */1,
                      tl: /* [] */0
                    }
                  }
                }
              }
            }
          },
          who: /* P2 */1,
          usedNothingP1: false,
          usedNothingP2: false
        }), 5, "Success!");

CS17SetupGame$Game.checkExpect(moveOfString("0", {
          board: {
            hd: /* Toad */0,
            tl: {
              hd: /* Toad */0,
              tl: {
                hd: /* Empty */2,
                tl: {
                  hd: /* Empty */2,
                  tl: {
                    hd: /* Frog */1,
                    tl: {
                      hd: /* Frog */1,
                      tl: /* [] */0
                    }
                  }
                }
              }
            }
          },
          who: /* P1 */0,
          usedNothingP1: false,
          usedNothingP2: false
        }), 0, "Success!");

function gameStatus(s) {
  var match = legalMoves(s);
  if (match) {
    return {
            TAG: /* Ongoing */1,
            _0: s.who
          };
  } else if (s.who === /* P1 */0) {
    return {
            TAG: /* Win */0,
            _0: /* P2 */1
          };
  } else {
    return {
            TAG: /* Win */0,
            _0: /* P1 */0
          };
  }
}

CS17SetupGame$Game.checkExpect(gameStatus({
          board: {
            hd: /* Toad */0,
            tl: {
              hd: /* Toad */0,
              tl: {
                hd: /* Empty */2,
                tl: {
                  hd: /* Empty */2,
                  tl: {
                    hd: /* Frog */1,
                    tl: {
                      hd: /* Frog */1,
                      tl: /* [] */0
                    }
                  }
                }
              }
            }
          },
          who: /* P1 */0,
          usedNothingP1: false,
          usedNothingP2: false
        }), {
      TAG: /* Ongoing */1,
      _0: /* P1 */0
    }, "Success!");

CS17SetupGame$Game.checkExpect(gameStatus({
          board: {
            hd: /* Frog */1,
            tl: {
              hd: /* Frog */1,
              tl: {
                hd: /* Empty */2,
                tl: {
                  hd: /* Toad */0,
                  tl: {
                    hd: /* Empty */2,
                    tl: {
                      hd: /* Toad */0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            }
          },
          who: /* P2 */1,
          usedNothingP1: false,
          usedNothingP2: true
        }), {
      TAG: /* Win */0,
      _0: /* P1 */0
    }, "Success!");

function nextState(s, m) {
  if (m !== 0) {
    var i = m - 1 | 0;
    var boardLength = List.length(s.board);
    var currGameSpace = List.nth(s.board, i);
    var endGameSpace;
    switch (currGameSpace) {
      case /* Toad */0 :
          endGameSpace = (i + 1 | 0) < boardLength && List.nth(s.board, i + 1 | 0) === /* Empty */2 ? i + 1 | 0 : i + 2 | 0;
          break;
      case /* Frog */1 :
          endGameSpace = (i - 1 | 0) >= 0 && List.nth(s.board, i - 1 | 0) === /* Empty */2 ? i - 1 | 0 : i - 2 | 0;
          break;
      case /* Empty */2 :
          endGameSpace = Pervasives.failwith("LEGAL MOVES CANNOT RETURN AN EMPTY SQUARE!");
          break;
      
    }
    var updateGameSpace = function (alod, index, v) {
      if (!alod) {
        return /* [] */0;
      }
      var tl = alod.tl;
      if (index !== 0) {
        if (index > 0) {
          return {
                  hd: alod.hd,
                  tl: updateGameSpace(tl, index - 1 | 0, v)
                };
        } else {
          return alod;
        }
      } else {
        return {
                hd: v,
                tl: tl
              };
      }
    };
    var match = s.who;
    return {
            board: updateGameSpace(updateGameSpace(s.board, i, /* Empty */2), endGameSpace, currGameSpace),
            who: match ? /* P1 */0 : /* P2 */1,
            usedNothingP1: s.usedNothingP1,
            usedNothingP2: s.usedNothingP2
          };
  }
  var match$1 = s.who;
  if (match$1) {
    return {
            board: s.board,
            who: /* P1 */0,
            usedNothingP1: s.usedNothingP1,
            usedNothingP2: true
          };
  } else {
    return {
            board: s.board,
            who: /* P2 */1,
            usedNothingP1: true,
            usedNothingP2: s.usedNothingP2
          };
  }
}

CS17SetupGame$Game.checkExpect(nextState({
          board: {
            hd: /* Frog */1,
            tl: {
              hd: /* Toad */0,
              tl: {
                hd: /* Empty */2,
                tl: {
                  hd: /* Frog */1,
                  tl: {
                    hd: /* Empty */2,
                    tl: {
                      hd: /* Toad */0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            }
          },
          who: /* P1 */0,
          usedNothingP1: false,
          usedNothingP2: true
        }, 2), {
      board: {
        hd: /* Frog */1,
        tl: {
          hd: /* Empty */2,
          tl: {
            hd: /* Toad */0,
            tl: {
              hd: /* Frog */1,
              tl: {
                hd: /* Empty */2,
                tl: {
                  hd: /* Toad */0,
                  tl: /* [] */0
                }
              }
            }
          }
        }
      },
      who: /* P2 */1,
      usedNothingP1: false,
      usedNothingP2: true
    }, "Success!");

CS17SetupGame$Game.checkExpect(nextState({
          board: {
            hd: /* Frog */1,
            tl: {
              hd: /* Toad */0,
              tl: {
                hd: /* Empty */2,
                tl: {
                  hd: /* Frog */1,
                  tl: {
                    hd: /* Empty */2,
                    tl: {
                      hd: /* Toad */0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            }
          },
          who: /* P1 */0,
          usedNothingP1: false,
          usedNothingP2: true
        }, 0), {
      board: {
        hd: /* Frog */1,
        tl: {
          hd: /* Toad */0,
          tl: {
            hd: /* Empty */2,
            tl: {
              hd: /* Frog */1,
              tl: {
                hd: /* Empty */2,
                tl: {
                  hd: /* Toad */0,
                  tl: /* [] */0
                }
              }
            }
          }
        }
      },
      who: /* P2 */1,
      usedNothingP1: true,
      usedNothingP2: true
    }, "Success!");

function estimateValue(s) {
  var currPlayer = gameStatus(s);
  if (currPlayer.TAG === /* Win */0) {
    if (currPlayer._0) {
      return -Pervasives.infinity;
    } else {
      return Pervasives.infinity;
    }
  }
  var lengthOfPossibleLegalMoves = List.length(legalMoves(s));
  var legalMovesDiff;
  if (currPlayer._0 === /* P1 */0) {
    var p2state_board = s.board;
    var p2state_usedNothingP1 = s.usedNothingP1;
    var p2state_usedNothingP2 = s.usedNothingP2;
    var p2state = {
      board: p2state_board,
      who: /* P2 */1,
      usedNothingP1: p2state_usedNothingP1,
      usedNothingP2: p2state_usedNothingP2
    };
    legalMovesDiff = Math.imul(lengthOfPossibleLegalMoves, 15) - Math.imul(List.length(legalMoves(p2state)), 15) | 0;
  } else {
    var p1state_board = s.board;
    var p1state_usedNothingP1 = s.usedNothingP1;
    var p1state_usedNothingP2 = s.usedNothingP2;
    var p1state = {
      board: p1state_board,
      who: /* P1 */0,
      usedNothingP1: p1state_usedNothingP1,
      usedNothingP2: p1state_usedNothingP2
    };
    legalMovesDiff = Math.imul(lengthOfPossibleLegalMoves, 15) - Math.imul(List.length(legalMoves(p1state)), 15) | 0;
  }
  var usedNothingDiff = (
    s.usedNothingP1 ? -75 : 75
  ) - (
    s.usedNothingP2 ? -75 : 75
  ) | 0;
  var boardLength = List.length(s.board);
  var advancementDiffCalc = function (_bd, _i, _acc) {
    while(true) {
      var acc = _acc;
      var i = _i;
      var bd = _bd;
      if (!bd) {
        return acc;
      }
      switch (bd.hd) {
        case /* Toad */0 :
            _acc = acc - Math.imul(15, i) | 0;
            _i = i + 1 | 0;
            _bd = bd.tl;
            continue ;
        case /* Frog */1 :
            _acc = acc - Math.imul(15, (i - boardLength | 0) - 1 | 0) | 0;
            _i = i + 1 | 0;
            _bd = bd.tl;
            continue ;
        case /* Empty */2 :
            _i = i + 1 | 0;
            _bd = bd.tl;
            continue ;
        
      }
    };
  };
  var tripleBlockScoreCalc = function (_bd, _acc) {
    while(true) {
      var acc = _acc;
      var bd = _bd;
      if (!bd) {
        return acc;
      }
      var match = bd.tl;
      if (!match) {
        return acc;
      }
      var match$1 = match.tl;
      if (!match$1) {
        return acc;
      }
      var hd3 = match$1.hd;
      var hd2 = match.hd;
      var changeInScore;
      switch (bd.hd) {
        case /* Toad */0 :
            changeInScore = hd2 >= 2 || hd3 >= 2 ? 0 : -30;
            break;
        case /* Frog */1 :
            changeInScore = hd2 >= 2 || hd3 >= 2 ? 0 : 30;
            break;
        case /* Empty */2 :
            changeInScore = 0;
            break;
        
      }
      _acc = acc + changeInScore | 0;
      _bd = {
        hd: hd2,
        tl: {
          hd: hd3,
          tl: match$1.tl
        }
      };
      continue ;
    };
  };
  var selfBlockScoreCalc = function (_bd, _acc) {
    while(true) {
      var acc = _acc;
      var bd = _bd;
      if (!bd) {
        return acc;
      }
      if (!bd.tl) {
        return acc;
      }
      switch (bd.hd) {
        case /* Toad */0 :
            var match = bd.tl;
            if (match.hd !== 0) {
              _bd = bd.tl;
              continue ;
            }
            _acc = acc - 15 | 0;
            _bd = {
              hd: /* Toad */0,
              tl: match.tl
            };
            continue ;
        case /* Frog */1 :
            var match$1 = bd.tl;
            if (match$1.hd !== 1) {
              _bd = bd.tl;
              continue ;
            }
            _acc = acc + 15 | 0;
            _bd = {
              hd: /* Frog */1,
              tl: match$1.tl
            };
            continue ;
        case /* Empty */2 :
            _bd = bd.tl;
            continue ;
        
      }
    };
  };
  return (((legalMovesDiff + usedNothingDiff | 0) + advancementDiffCalc(s.board, 1, 0) | 0) + tripleBlockScoreCalc(s.board, 0) | 0) + selfBlockScoreCalc(s.board, 0) | 0;
}

CS17SetupGame$Game.checkExpect(estimateValue({
          board: {
            hd: /* Frog */1,
            tl: {
              hd: /* Frog */1,
              tl: {
                hd: /* Empty */2,
                tl: {
                  hd: /* Toad */0,
                  tl: {
                    hd: /* Empty */2,
                    tl: {
                      hd: /* Toad */0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            }
          },
          who: /* P2 */1,
          usedNothingP1: true,
          usedNothingP2: true
        }), Pervasives.infinity, "Success!");

CS17SetupGame$Game.checkExpect(estimateValue({
          board: {
            hd: /* Frog */1,
            tl: {
              hd: /* Frog */1,
              tl: {
                hd: /* Empty */2,
                tl: {
                  hd: /* Empty */2,
                  tl: {
                    hd: /* Toad */0,
                    tl: {
                      hd: /* Toad */0,
                      tl: /* [] */0
                    }
                  }
                }
              }
            }
          },
          who: /* P1 */0,
          usedNothingP1: true,
          usedNothingP2: true
        }), -Pervasives.infinity, "Success!");

CS17SetupGame$Game.checkError((function (param) {
        return moveOfString("X", {
                    board: {
                      hd: /* Toad */0,
                      tl: {
                        hd: /* Toad */0,
                        tl: {
                          hd: /* Empty */2,
                          tl: {
                            hd: /* Empty */2,
                            tl: {
                              hd: /* Frog */1,
                              tl: {
                                hd: /* Frog */1,
                                tl: /* [] */0
                              }
                            }
                          }
                        }
                      }
                    },
                    who: /* P1 */0,
                    usedNothingP1: false,
                    usedNothingP2: false
                  });
      }), "NEED TO INPUT AN INTEGER!");

CS17SetupGame$Game.checkError((function (param) {
        return moveOfString("10", {
                    board: {
                      hd: /* Toad */0,
                      tl: {
                        hd: /* Toad */0,
                        tl: {
                          hd: /* Empty */2,
                          tl: {
                            hd: /* Empty */2,
                            tl: {
                              hd: /* Frog */1,
                              tl: {
                                hd: /* Frog */1,
                                tl: /* [] */0
                              }
                            }
                          }
                        }
                      }
                    },
                    who: /* P1 */0,
                    usedNothingP1: false,
                    usedNothingP2: false
                  });
      }), "ILLEGAL MOVE!");

CS17SetupGame$Game.checkError((function (param) {
        return moveOfString("3", {
                    board: {
                      hd: /* Toad */0,
                      tl: {
                        hd: /* Toad */0,
                        tl: {
                          hd: /* Empty */2,
                          tl: {
                            hd: /* Empty */2,
                            tl: {
                              hd: /* Frog */1,
                              tl: {
                                hd: /* Frog */1,
                                tl: /* [] */0
                              }
                            }
                          }
                        }
                      }
                    },
                    who: /* P1 */0,
                    usedNothingP1: false,
                    usedNothingP2: false
                  });
      }), "ILLEGAL MOVE!");

var TNF = {
  stringOfPlayer: stringOfPlayer,
  stringOfState: stringOfState,
  stringOfMove: stringOfMove,
  initialState: initialState,
  legalMoves: legalMoves,
  gameStatus: gameStatus,
  nextState: nextState,
  moveOfString: moveOfString,
  estimateValue: estimateValue
};

var MyGame = TNF;

exports.TNF = TNF;
exports.MyGame = MyGame;
/*  Not a pure module */
